# tbl
in="$1"
# sysnum.h
out1="$2"
# sysfunc,h
out2="$3"
# sysdecl.h
out3="$4"
# usys.pl
out4="$5"
# sys_name.h
out5="$6"
# loongarch_usys.pl
out6="$7"

grep '^[0-9]' "$in" | sort -n | (
    while read nr name entry; do
	if [ -n "$entry" ]; then
	    echo "#define SYS_$name $nr"
	fi
    done
) > "$out1"

grep '^[0-9]' "$in" | sort -n | (
    while read nr name entry; do
	if [ -n "$entry" ]; then
	    echo "[SYS_$name] $entry,"
	fi
    done
) > "$out2"

grep '^[0-9]' "$in" | sort -n | (
    while read nr name entry; do
	if [ -n "$entry" ]; then
		echo "extern uint64 $entry(void);"
	fi
    done
) > "$out3"

# $5: usys.pl

cat > "$out4" <<EOF
#!/usr/bin/perl -w
# generated by gen_syscall.sh - do not edit

print "#include \\"syscall.h\\"\n";

sub entry {
    my \$name = shift;
    print ".global \$name\\n";
    print "\${name}:\\n";
    print " li a7, SYS_\${name}\\n";
    print " ecall\\n";
    print " ret\\n";
}
EOF

grep '^[0-9]' "$in" | sort -n | (
    while read nr name entry; do
	if [ -n "$entry" ]; then
	    echo "entry(\"$name\");"
	fi
    done
) >> "$out4"


grep '^[0-9]' "$in" | sort -n | (
    echo 'const char *syscall_name[] = {'
    while read nr name entry; do
        if [ -n "$entry" ]; then
            echo "    [SYS_$name] = \"$entry\","
        fi
    done
    echo '};'
) > "$out5"


# $7: loongarch_usys.pl
cat > "$out6" <<EOF
#!/usr/bin/perl -w
# generated by gen_syscall.sh - do not edit
print "#include \\"syscall.h\\"\n";

sub entry {
    my \$name = shift;
    print ".global \$name\n";
    print "\${name}:\n";
    print " li.d \\\$a7, SYS_\${name}\n";
    print " syscall 0\\n";
    print " jirl \\\$zero, \\\$ra, 0\\n";
}
EOF

grep '^[0-9]' "$in" | sort -n | (
    while read nr name entry; do
	if [ -n "$entry" ]; then
	    echo "entry(\"$name\");"
	fi
    done
) >> "$out6"

