#!/usr/bin/perl -w
# generated by gen_syscall.sh - do not edit

print "#include \"syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
entry("fork");
entry("dev");
entry("wait");
entry("pipe");
entry("read");
entry("kill");
entry("exec");
entry("fstat");
entry("chdir");
entry("dup");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("open");
entry("mknod");
entry("unlink");
entry("link");
entry("mkdir");
entry("close");
entry("openat");
entry("write");
entry("readlinkat");
entry("fstatat");
entry("exit");
entry("set_tid_address");
entry("set_robust_list");
entry("nanosleep");
entry("sched_yield");
entry("sigaction");
entry("setgid");
entry("setuid");
entry("times");
entry("uname");
entry("gettimeofday");
entry("getpid");
entry("getppid");
entry("getuid");
entry("getgid");
entry("brk");
entry("munmap");
entry("clone");
entry("execve");
entry("mmap");
entry("wait4");
entry("prlimit64");
entry("getrandom");
